var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                       y                               y                        ",
   "                   f  yyy                             yyy                       ",
   "                     yyyyy            y              yyyyy                      ",
   "                                     yyy                                        ",
   "                                    yyyyy                                       ",
   "                                              o                          xxxxxxx",
   "                                    o o      xx    xx                    x!!!!!!",
   "            y                                          q       v                ",
   "           yyy                     xxxxxxx                                      ",
   " @        yyyyy                                       xxxx               xxxxxxx",
   "rrr                         xxxx              o o                        x      ",
   "  x                     o                                            o   x      ",
   "  x                    xxx                  xxxxx                  xxxx  x      ",
   "  x                    xxx                                   xxx         x      ",
   "  x                    xxx                           o       xxx         x      ",
   "  xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    t       xxxxxxxxxxxxx      ",
   "            x   x                               x            x                  ",
   "            x!!!x                               x!!!!!!!!!!!!x                  ",
   "            x!!!x                               x!!!!!!!!!!!!x                  ",
   "            xxxxx                               xxxxxxxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                              x                    ",
   "                      y                                                               y       x                    ",
   "                     yyy                                                             yyy      x                    ",
   "                    yyyyy                f                y                         yyyyy     x                    ",
   "                                                         yyy                                  x              y     ",
   "     y                                                  yyyyy                                 x             yyy    ",
   "    yyy                                          xxx                                          x            yyyyy   ",
   "   yyyyy                                        x!!!x                                         x      xxxxx         ",
   "                                                 xvx                                          x     x     x        ",
   "                    xxxx             xxxx                                                     x     x     xxx      ",
   "              o                                       o                     y                 x     x  o           ",
   "             xxxx           xxxx        y      xo    xx                    yyy                x     x  x           ",
   "                                       yyy     xx     x                   yyyyy               x     x     rrx      ",
   "            y                         yyyyy    x      x                                       x     x!!!!!x        ",
   "           yyy                                 x      x                                     l x      xxxxx         ",
   "          yyyyy                                x     ox                                       x                    ",
   "                                               x    xxx                             xx     xxxx                    ",
   "                        o                      x      x      o  o     x   x         x         x                    ",
   "                                               x      x                             x         x                    ",
   "                       xxx                     xo           xxxxxx            xxxxx xxx       x                    ",
   "                  o          o                 xxx                            x               x                    ",
   "                 xxx        xxx            x         xxx                         x                                 ",
   "     @                                     x          x                         xxxxx   xxxxx                      ",
   "    rrr     xxxx                xxxx     xxx          x         x               x     o     x         xxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            xxxx      x!!!!!!!!!!!!!!!x     =     x         x!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x!!!!!!!!!!!!!!!xxxxx   xxxxx    o o xx!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    o                 x!!!!!!!!!!!!!!!!!!!x                xx!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                     xx!!!!!!!!!!!!!!!!!!!x          xxxxxxx!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            =         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!xx!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

  ["                                                                                                              ",
   "                                                                                             y                ",
   "                                                                                            yyy               ",
   "                                                                                           yyyyy              ",
   "                                                                                                              ",
   "                                 o                          f                                                 ",
   "                                                 y                             xxxxxxxxx                      ",
   "                                                yyy                                    x                      ",
   "          y                   xxxxxxx          yyyyy                        y          x                      ",
   "         yyy               xxxx     xxxx                                   yyy    q    x                      ",
   "        yyyyy             xx    y      xx                                 yyyyy        x                      ",
   "                         xx |  yyy      xx                          xxxx         xpp   x                      ",
   "                         x    yyyyy      x                     o                       x                      ",
   "                                                             xxxx           xxxxxxxxxxxx                      ",
   "                 x               o                                                                            ",
   "                                 x                                                              y             ",
   "                         x               rrr    xxxx                                           yyy            ",
   "        y                xx          |  xx              xxxx                                  yyyyy           ",
   "       yyy                xx!!!!!!!!!!!xx                                     y                               ",
   "      yyyyy                xxxx!!!!!xxxx                                     yyy                              ",
   "                              xxxxxxx                                       yyyyy                             ",
   "                                                                                                              ",
   "                                               y                                                              ",
   "                                              yyy                             y                               ",
   "        l                                    yyyyy         xxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "                      o                                    x                yyyyy          |     x            ",
   "       xxx            xx                                   x                         o           x            ",
   "                x      x                                   x                        xxx          x            ",
   "                xo     x           y                       x          xx                         x            ",
   "                xxx    x          yyy                      x o   =    xx       |                 x            ",
   "                x      x         yyyyy                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx            ",
   "                x     ox                                                                           v          ",
   "       y        x    xxx                                                                           y          ",
   "      yyy       x      x                                                 xxxxx                    yyy         ",
   " x   yyyyy      x      x                                                 x   x                   yyyyy     o  ",
   " x              xo                  x!!!!!xxxxxxx       y                x   x                             x  ",
   " x              xxx           xxxxxxx!!!!!x            yyy               x xox                             x  ",
   " x                            x!!!!!!!!!!!x           yyyyy              x xxx                             x  ",
   " x                            x!!!!!!!!!!!x                              x     x                    xxx    x  ",
   " x                 x!x!!      x!!!!!!!!!!!x                              x     x                    xxx    x  ",
   " x               xx!!!xx!     x!!!!!!!!!!!x                             rxxxxxxx  x!!!x                    x  ",
   " x               x!!!!!x!!    x!!!!!!!!!!!x =  oo  =xx   oo=  xx   oo =            xxx          xxx        x  ",
   " x             xxx!!!!!xx!!!  xxxxxxxxxxxxx!!!!xx!!!!!!!!xx!!!!!!!!xx!                          xxx        x  ",
   " x      @     x!!!!!!!!!xx!! x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                  x  ",
   " xrrrrrrrrrrrrrxxxxxxxxxxx!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   " !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

   ["            y                                      y                            ",
    "           yyy                                    yyy                           ",
    "          yyyyy                                  yyyyy                          ",
    "                                     f                                          ",
    "                                                                                ",
    "                      y  y               y         y  y        y                ",
    "                      y  y               y         y           y         y      ",
    "                      yyyy yyyy y  y     y         y  y yyyy   y        yyy     ",
    "                         y y  y y  y     y    y    y  y y  y   y       yyyyy    ",
    "            y            y y  y y  y     y   y y   y  y y  y                    ",
    "           yyy        yyyy yyyy yyyy     yyyy   yyyy  y y  y   y                ",
    "          yyyyy                                                                 ",
    "                                                                                ",
    "                                      @                                         ",
    "                                   xxxxxxx                                      ",
    "                                   x!!!!!x                                      ",
    "                                   x!!!!!x                                      ",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
    "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
