var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                              o                          xxxxxxx",
   "                                    o o      xx    xx       y            x!!!!!!",
   "            y                                                  v                ",
   "           yyy                     xxxxxxx                                      ",
   " @        yyyyy                                       xxxx               xxxxxxx",
   "xrx                         xxxx              o o                        x      ",
   "  x                     o                                            o   x      ",
   "  x                q   xxx               y  xxxxx                  xxxx  x      ",
   "  x                    xxx                                   xxx         x      ",
   "  x q                  xxx                           o       xxx         x      ",
   "  xxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    t       xxxxxxxxxxxxx      ",
   "            x   x                               x            x                  ",
   "            x!!!x                               x!!!!!!!!!!!!x                  ",
   "            x!!!x                               x!!!!!!!!!!!!x                  ",
   "            xxxxx                               xxxxxxxxxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                 xxx                                                                 ",
   "                                                x!!!x                                         x                      ",
   "                                                 xvx                                          x                      ",
   "                    xxx              xxx                                                      x                    ",
   "              o                                       o                                       x                    ",
   "             xxx            xxx                xo    xx                                       x                    ",
   "                                               xx     x                                       x                    ",
   "                                               x      x                                       x                    ",
   "                                               x     ox                                     g x                    ",
   "                                               x    xxx                             xx     xxxx                    ",
   "                        o                      x      x      o  o     x   x         x         x                    ",
   "                                               x      x                             x         x                    ",
   "                       xxx                     xo           xxxxxx            xxxxx xxx       x                    ",
   "                  o          o                 xxx                            x               x                    ",
   "     @           xxx        xxx            x         xxx                         x                                 ",
   "                                           x          x                         xxxxx   xxxxx                      ",
   "    xrx     xxxx                xxxx     xxx          x         x               x     o     x          xxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            xxxx      x!!!!!!!!!!!!!!!x     =     x         x!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x!!!!!!!!!!!!!!!xxxxx   xxxxx    o o xx!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    o                 x!!!!!!!!!!!!!!!!!!!x                xx!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                     xx!!!!!!!!!!!!!!!!!!!x          xxxxxxx!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            =         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx!!!!xx!!!xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                              xxxxxxxxxxxxxxxxxx                                                              ",
   "                             x                                                                                ",
   "                            x                                                                                 ",
   "                           x                                                                                  ",
   "                 xxx!!!!!!x                                                                                   ",
   "                 x                                             o                                              ",
   "                          o              xxx                    xxxx                                          ",
   "                                                xxxxxx                                                        ",
   "                                    o           x                                                             ",
   "                                   xxx         x                                                              ",
   "                         xxxx  |        |     x                                                               ",
   "                        o    x               x                                                                ",
   "                      xxx     xxxxxxxxx  xxxx                                                                 ",
   "                                      xxxx                                                                    ",
   "                   o                                                                                          ",
   "                  xxxx                                                                                        ",
   "                                                                                                              ",
   "                         o                                                                                    ",
   "                         xx                                                                                   ",
   "                   o                                                                                          ",
   "                  xx                                                                                          ",
   "                         o                                                                                    ",
   "                        xxx                                                                                   ",
   "                   o                                                                                          ",
   "                  xxx                                                                                         ",
   "  x                                                                                                     x x   ",
   "  x                                       xxxxxxx                        xxxxx                             x  ",
   "  x                     xxx                x                              x   x                            x  ",
   "  x                                        x                              x x x                            x  ",
   "  x                           !!!!         x                           xxx xxx                             x  ",
   "  x                xxx        !!!!        x                              x         xxx                     x  ",
   "  x              xxxxxxx      !!!!        x                             xxx       x!!!x          x         x  ",
   "  x              x!!!!!x      !!!!        x                             x x        xxx          xxx        x  ",
   "  x            xxx!!!!!xxx    xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @     x!!!!!!!!!x    x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxrxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],

  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
